"""Render the analysis outputs into two standalone HTML pages.

output/results.html  - all collocation tables (one per run) on one page
output/kwic.html     - concordance lines for the discussed collocates

Run from the repository root:  python code/build_html.py
"""
import html

import pandas as pd

TARGET = "内阁"
RUNS = [
    ("collocates_window5.csv", "window, horizon = 5"),
    ("collocates_window10.csv", "window, horizon = 10"),
    ("collocates_sentence.csv", "sentence"),
]
TOP_N = 30
KWIC_ROWS_PER_NODE = 60

STYLE = """
body { font-family: "Songti SC", "Noto Serif CJK SC", serif; max-width: 1100px;
       margin: 2rem auto; padding: 0 1rem; line-height: 1.6; color: #222; }
h1 { border-bottom: 3px double #6b2d2d; padding-bottom: .4rem; }
h2 { color: #6b2d2d; margin-top: 2.2rem; }
table { border-collapse: collapse; margin: 1rem 0; font-size: .9rem; width: 100%; }
th, td { border: 1px solid #ccc; padding: .25rem .5rem; text-align: right; }
th:first-child, td:first-child, th:nth-child(2), td:nth-child(2) { text-align: left; }
th { background: #f3e9e0; }
.collocate { font-weight: bold; }
.node { color: #6b2d2d; font-weight: bold; }
.kwic td { text-align: right; font-size: .9rem; }
.kwic .l { text-align: right; color: #555; }
.kwic .r { text-align: left; color: #555; }
.juan { color: #888; white-space: nowrap; }
.note { color: #666; font-size: .9rem; }
"""


def esc(x):
    return html.escape(str(x))


def results_page():
    parts = [
        "<!DOCTYPE html><html lang='zh'><head><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        f"<title>Collocates of {TARGET} in the Mingshi</title>",
        f"<style>{STYLE}</style></head><body>",
        f"<h1>Collocates of {TARGET} in the <em>Mingshi</em> 明史</h1>",
        "<p>Target word: <span class='collocate'>"
        f"{esc(TARGET)}</span> (simplified). Method: qhchina "
        "<code>find_collocates</code>, Fisher's exact test, "
        "FDR-BH correction (<code>max_adjusted_p=0.05</code>), "
        "classical-Chinese stopwords, <code>min_word_length=2</code>, "
        "measures <code>log_likelihood</code> and <code>logDice</code>. "
        f"Tables show the top {TOP_N} collocates per run, ranked by "
        "log-likelihood.</p>",
    ]
    for filename, label in RUNS:
        full = pd.read_csv(f"output/{filename}")
        df = full.sort_values("log_likelihood", ascending=False).head(TOP_N).copy()
        df["rank_ll"] = range(1, len(df) + 1)
        df["rank_ld"] = df["log_dice"].rank(ascending=False).astype(int)
        parts.append(f"<h2>{esc(label)} &mdash; {len(full)} "
                     "significant collocates</h2>")
        parts.append("<table><tr><th>#</th><th>collocate</th>"
                     "<th>obs (window)</th><th>expected</th>"
                     "<th>log-likelihood</th><th>logDice</th>"
                     "<th>rank by logDice</th><th>adj. p</th></tr>")
        for _, r in df.iterrows():
            parts.append(
                "<tr>"
                f"<td>{r['rank_ll']}</td>"
                f"<td class='collocate'>{esc(r['collocate'])}</td>"
                f"<td>{r['obs_local']:g}</td>"
                f"<td>{r['exp_local']:.3g}</td>"
                f"<td>{r['log_likelihood']:.1f}</td>"
                f"<td>{r['log_dice']:.2f}</td>"
                f"<td>{r['rank_ld']}</td>"
                f"<td>{r['adjusted_p_value']:.2g}</td>"
                "</tr>")
        parts.append("</table>")
    parts.append("<p class='note'>Generated by <code>code/build_html.py</code>."
                 "</p></body></html>")
    return "\n".join(parts)


def kwic_page():
    df = pd.read_csv("output/kwic.csv", dtype=str).fillna("")
    parts = [
        "<!DOCTYPE html><html lang='zh'><head><meta charset='utf-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1'>",
        f"<title>KWIC for collocates of {TARGET}</title>",
        f"<style>{STYLE}</style></head><body>",
        f"<h1>Concordances (KWIC) &mdash; collocates of {esc(TARGET)}</h1>",
        "<p>Each line: 卷 (juan) | left context | node | right context. "
        f"Up to {KWIC_ROWS_PER_NODE} lines per node are shown.</p>",
    ]
    for node, group in df.groupby("node", sort=False):
        parts.append(f"<h2>{esc(node)} &mdash; {len(group)} lines</h2>")
        parts.append("<table class='kwic'>")
        for _, r in group.head(KWIC_ROWS_PER_NODE).iterrows():
            parts.append(
                "<tr>"
                f"<td class='juan'>{esc(r['juan'])}</td>"
                f"<td class='l'>{esc(r['left'])}</td>"
                f"<td class='node'>[{esc(r['node'])}]</td>"
                f"<td class='r'>{esc(r['right'])}</td>"
                "</tr>")
        parts.append("</table>")
    parts.append("<p class='note'>Generated by <code>code/build_html.py</code>."
                 "</p></body></html>")
    return "\n".join(parts)


def main():
    open("output/results.html", "w", encoding="utf-8").write(results_page())
    open("output/kwic.html", "w", encoding="utf-8").write(kwic_page())
    print("wrote output/results.html and output/kwic.html")


if __name__ == "__main__":
    main()
